import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import logo from './../../images/logo.branca.png'
import Popup from '@/components/popup'
import { useState } from 'react'
import menuBar from './../../images/menubar.png'
import Start from '@/components/home'
import Portfolio from '@/components/portfolio'
import Footer from '@/components/footer'
import Depositions from '@/components/depositions'
import About from '@/components/about'
import Process from '@/components/process'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [openModal, setOpenModal] = useState(false)

  return (
    <>
      <Head>
        <title> UISAX </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <header className={styles.headerdesktop}>
        <div className={styles.header}>
          <div className={styles.logo}>
            <a href="#home">
              <Image src={logo} alt="Logo" width={120} height={25}/>
            </a>
          </div>
          <div className={styles.page}>
            <a href="#home"> Home </a>
            <a href=""> Sobre </a>
            <a href=""> Contato </a>
            <a href="#portfolio"> Portfólio </a>
            <a href="https://api.whatsapp.com/send?phone=5537999386357&text=Ol%C3%A1,%20tudo%20bem?">
              <button > ORÇAMENTO </button>
            </a>
          </div>
        </div>
      </header>
      <header id='home' className={styles.headermobile}>
        <div className={styles.headermobilesub}>
          <div className={styles.logo}>
            <Image src={logo} alt="Logo" width={80} height={18}/>
          </div>
          <div className={styles.iconMenuBar}>
            <button onClick={() => setOpenModal(true)}> <Image src={menuBar} alt="Icone Menu Bar"
              width={30} height={30}></Image>
            </button>
          </div>
          <Popup isOpen={openModal} setModalOpen={() => setOpenModal(!openModal)}> </Popup>
          <div className={styles.buttonn}>
            <a href="https://api.whatsapp.com/send?phone=5537999386357&text=Ol%C3%A1,%20tudo%20bem?">
              <button > ORÇAMENTO </button>
            </a>
          </div>
        </div>
      </header>
      <section id='home'>
        <Start/>
      </section>
      <section>
        <About/>
      </section>
      <section id='portfolio'>
        <Portfolio/>
      </section>
      <section>
        <Depositions/>
      </section>
      <section id='process'>
        <Process/>
      </section>
      {/*<Depoimentos/>*/}
      <Footer/>
    </>
  )
}
